### ISSUE TITLE
Severe Error in JSystem agent

### ISSUE THREAD

**Issue by aaroncelt** [Top-Q/jsystem#243]
Hi 
Can anybody help me with an error in the Jsystem agent.
I'm attempting to set up  jsystem agents and use Jsystem  in a distributed environment using VM's with windows 7 installed.

Any help would be greatly appreciated.

C:\DevEnv\jsystem-master\jsystem-master\jsystem-assembly\jsystem-runner\target\r
unner\runner>runAgent

C:\DevEnv\jsystem-master\jsystem-master\jsystem-assembly\jsystem-runner\target\r
unner\runner>set JSYSTEM_MAIN=jsystem.runner.agent.server.RunnerAgentMain

C:\DevEnv\jsystem-master\jsystem-master\jsystem-assembly\jsystem-runner\target\r
unner\runner>set JMX=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremo
te.port=8999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.managem
ent.jmxremote.ssl.need.client.auth=false -Dcom.sun.management.jmxremote.ssl=fals
e

C:\DevEnv\jsystem-master\jsystem-master\jsystem-assembly\jsystem-runner\target\r
unner\runner>call "C:\DevEnv\jsystem-master\jsystem-master\jsystem-assembly\jsys
tem-runner\target\runner\runner\\runBase.bat"
Jun 02, 2015 3:25:47 PM jsystem.framework.JSystemProperties initLogger
INFO: Logger was init
Jun 02, 2015 3:25:47 PM jsystem.runner.agent.server.RunnerAgentMain run
INFO: Starting JSystem agent activation ...
Jun 02, 2015 3:25:47 PM jsystem.framework.RunProperties <init>
INFO: create run properties at :C:\DevEnv\jsystem-master\jsystem-master\jsystem-
assembly\jsystem-runner\target\runner\runner\.run.properties

15:25:48: Agent id is2fb4941f-efa1-447f-98a9-6865062c1677
Jun 02, 2015 3:25:48 PM jsystem.runner.agent.server.RunnerAgentMain startRunner
SEVERE: Error in jsystem agent.
java.io.FileNotFoundException: res\conf\ftpd.properties (The system cannot find
the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at com.aqua.filetransfer.ftp.FTPServer.getConfiguration(FTPServer.java:1
36)
        at com.aqua.filetransfer.ftp.FTPServer.init(FTPServer.java:73)
        at jsystem.runner.agent.server.RunnerAgentMain.initAgent(RunnerAgentMain
.java:83)
        at jsystem.runner.agent.server.RunnerAgentMain.run(RunnerAgentMain.java:
61)
        at jsystem.runner.agent.server.RunnerAgentMain.startRunner(RunnerAgentMa
in.java:108)
        at jsystem.framework.launcher.Launcher2.run(Launcher2.java:78)
        at jsystem.framework.launcher.Launcher2.main(Launcher2.java:31)

Log backup process ... (don't close)
Press any key to continue . . .

**Comment by itaiag** [comment]
I'm sorry to say that the agents mechanism is a deprecated feature. In many cases, one can achieve better results using CI agents like Jenkins or by implementing a dedicated agent.
