### ISSUE TITLE
Getting error on reporter when running in mvn

### ISSUE THREAD

**Issue by itay85** [Top-Q/jsystem#285]
mvn jsystem:run -Dscenario=scenarios/default -Dsut=mysut.xml

execute scenario:
t0:
  [jsystem] Failed in remote execution.
Dec 12, 2016 11:13:35 AM jsystem.framework.report.RunnerListenersManager report
SEVERE: Fail to report
java.lang.NullPointerException
        at jsystem.extensions.report.difido.AbstractHtmlReporter.report(AbstractHtmlReporter.java:175)
        at jsystem.framework.report.RunnerListenersManager.report(RunnerListenersManager.java:1486)
        at jsystem.framework.report.DefaultReporterImpl.report(DefaultReporterImpl.java:107)
        at jsystem.framework.report.DefaultReporterImpl.report(DefaultReporterImpl.java:55)

Caused by: C:\Automation\trunk\work-tests\target\classes\scenarios\default.xml:26: java.lang.ClassNotFoundException: jsystem.runner.agent.clients.DefaultDistributedExecutionPlugin

i'm getting the above error when running with maven , Is something wrong with what i'm doing?

**Comment by itaiag** [comment]
The **DefaultDistributedExecutionPlugin** is part of the **jsystemAgent** artifiact. It seems that from some reason it is not part of the dependencies that are used by the JSystem Maven plugin on your environment.

Please try to open the POM file of your test project and add the **jsystemAgent** as dependency to the **jsystem-maven-plugin**

```XML
<dependency>
    <groupId>org.jsystemtest</groupId>
    <artifactId>jsystemAgent</artifactId>
    <version>${jsystem.version}</version>
</dependency
```

**Comment by itay85** [comment]
yeap , adding it resolved the issue

**Comment by itay85** [comment]
Also getting this at the end of the run  after report is done 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.062 s
[INFO] Finished at: 2016-12-12T18:14:22+02:00
[INFO] Final Memory: 23M/372M
[INFO] ------------------------------------------------------------------------
Exception in thread "DefaultShutdownHook" java.lang.NoClassDefFoundError: jsystem/framework/system/SystemObjectCloseThread
        at jsystem.framework.system.SystemManagerImpl.closeAllObjects(SystemManagerImpl.java:441)
        at jsystem.framework.DefaultShutdownHook.run(DefaultShutdownHook.java:22)
Caused by: java.lang.ClassNotFoundException: jsystem.framework.system.SystemObjectCloseThread
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 2 more

**Comment by itay85** [comment]
I'm not sure what I have changed but suddenly I cannot find scenarios name: 
mvn jsystem:run -Dscenario:scenarios/default -Dsut:sut.xml
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ui-tests 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jsystem-maven-plugin:6.1.06-SNAPSHOT:run (default-cli) @ui-tests ---
[ERROR] Please specify a valid scenario name. Scenario can't be null
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.453 s
[INFO] Finished at: 2016-12-22T14:03:50+02:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsystemtest:jsystem-maven-plugin:6.1.06-SNAPSHOT:run (default-cli) on project ui-tests: Please specify a valid scenario name. Scenario can't be null -> [Help 1]

**Comment by igivon** [comment]
the same happens to me, check it:
- jsystem 6.1.06
- 2 X different project
Exception in thread "DefaultShutdownHook" java.lang.NoClassDefFoundError: jsystem/framework/system/SystemObjectCloseThread
        at jsystem.framework.system.SystemManagerImpl.closeAllObjects(SystemManagerImpl.java:441)
        at jsystem.framework.DefaultShutdownHook.run(DefaultShutdownHook.java:22)
Caused by: java.lang.ClassNotFoundException: jsystem.framework.system.SystemObjectCloseThread
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 2 more
