### ISSUE TITLE
ClassCastException on "Edit Scenario"

### ISSUE THREAD

**Issue by Betlista** [Top-Q/jsystem#291]
1. I downloaded JSystem 6.1.05.
2. I created new empty project using archetype (same version) - tests, not SO
3. mvn clean compile on project
4. I tried to switch project to that tests project
5. When I tried "Edit Scenario" on default scenario I got ClassCastException

java.lang.ClassCastException: jsystem.treeui.exceleditor.ExcelScenarioEditor cannot be cast to jsystem.framework.scenario.ScenarioEditor
	at jsystem.framework.scenario.SenarioEditorManager.getDuplicator(SenarioEditorManager.java:23)
	at jsystem.treeui.teststable.TestsTableController$2.run(TestsTableController.java:1306)

**Comment by Betlista** [comment]
I tried the same with 6.1.04 and same result.

**Comment by itaiag** [comment]
The edit scenario feature was a feature that allows users to edit the scenario as excel sheets, bit it was not working properly since the introduction of flow control and if conditions in JSystem.
Most of the feature was removed in 2013 as part of the #171 issue since there was a need to allow users to add the POI dependencies to projects without causing version conflicts with the POI version that was required for the feature.
To make story short, this feature is deprecated.

**Comment by itaiag** [comment]
There is still need to remove the icon from the toolbar.
