### ISSUE TITLE
Maven plugin cant close all system objects due to exception

### ISSUE THREAD

**Issue by iSvyat** [Top-Q/jsystem#326]
Maven plugin cant close all system objects after finishing scenario execution due to exception:

Exception in thread "DefaultShutdownHook" java.lang.NoClassDefFoundError: jsystem/framework/system/SystemObjectCloseThread
	at jsystem.framework.system.SystemManagerImpl.closeAllObjects(SystemManagerImpl.java:441)
	at jsystem.framework.DefaultShutdownHook.run(DefaultShutdownHook.java:22)
Caused by: java.lang.ClassNotFoundException: jsystem.framework.system.SystemObjectCloseThread
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 2 more

**Comment by itaiag** [comment]
Duplicated with issue #227
